---
- name: install php
  apt: name=php5 state=present
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php
- name: global composer
  shell: mv composer.phar /usr/local/bin/composer
